name: build

on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j $(nproc)
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build/afl-search
            build/afl-utils
            build/afl-copy
